import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#faf8f4' },
  container: { flex: 1, padding: 18 },
  headerCard: { backgroundColor: '#f2ede4', padding: 18, borderRadius: 18, marginBottom: 18, borderWidth: 1, borderColor: '#e8dfd4' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  logoText: { fontSize: 20, fontWeight: '900', color: '#3d2c1e', letterSpacing: -0.5 },
  subtitleText: { fontSize: 11, color: '#9e8c7a', marginTop: 2 },
  logoutButton: { backgroundColor: '#e8dfd4', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  logoutButtonText: { color: '#9e8c7a', fontSize: 12, fontWeight: '600' },
  welcomeText: { fontSize: 18, fontWeight: '700', color: '#3d2c1e', marginTop: 12 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#e8dfd4', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 20, gap: 6 },
  statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#c47d4a' },
  statusText: { color: '#7a5a3a', fontSize: 11, fontWeight: '600' },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: '#3d2c1e', marginBottom: 10 },
  
  mapContainer: { 
    flex: 1, 
    minHeight: 300, 
    backgroundColor: '#ffffff',
    borderRadius: 16, 
    overflow: 'hidden', 
    position: 'relative', 
    borderWidth: 1, 
    borderColor: '#e0d8cc' 
  },
  
  mapImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  robot: { position: 'absolute', width: 26, height: 26, borderRadius: 13, backgroundColor: '#c47d4a', borderWidth: 3, borderColor: '#faf8f4', zIndex: 2 },
  targetDot: { position: 'absolute', width: 8, height: 8, borderRadius: 4, backgroundColor: '#3d2c1e', zIndex: 1, opacity: 0.5 },
  tipText: { fontSize: 11, color: '#b0a090', textAlign: 'center', marginTop: 8, marginBottom: 14 },
  controlPanel: { backgroundColor: '#fff', padding: 16, borderRadius: 18, borderWidth: 1, borderColor: '#ede5d8' },
  coordInfoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  coordLabel: { fontSize: 13, color: '#9e8c7a', fontWeight: '500' },
  coordValue: { fontSize: 13, color: '#3d2c1e', fontWeight: '700' },
  callButton: { backgroundColor: '#3d2c1e', paddingVertical: 15, borderRadius: 12, alignItems: 'center', marginBottom: 10 },
  callButtonText: { color: '#faf8f4', fontSize: 15, fontWeight: '700' },
  subButtonRow: { flexDirection: 'row', justifyContent: 'space-between' },
  subButton: { flex: 0.48, backgroundColor: '#faf6f0', paddingVertical: 12, borderRadius: 10, alignItems: 'center', borderWidth: 1, borderColor: '#e8dfd4' },
  subButtonText: { color: '#7a5a3a', fontSize: 13, fontWeight: '600' },
  qrActiveButton: { backgroundColor: '#f5ede0', borderColor: '#c47d4a' },
  qrActiveText: { color: '#c47d4a', fontWeight: '700' },
  modalBackground: { flex: 1, backgroundColor: 'rgba(61, 44, 30, 0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: '#faf8f4', width: '85%', padding: 28, borderRadius: 22, alignItems: 'center', borderWidth: 1, borderColor: '#ede5d8' },
  modalTitle: { fontSize: 22, fontWeight: '800', color: '#3d2c1e', marginBottom: 8 },
  modalSubtitle: { fontSize: 13, color: '#9e8c7a', marginBottom: 22, textAlign: 'center' },
  qrWrapper: { padding: 16, backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e8dfd4', marginBottom: 18 },
  orderNumberText: { fontSize: 15, fontWeight: '700', color: '#c47d4a', marginBottom: 22 },
  closeButton: { backgroundColor: '#f2ede4', paddingVertical: 13, width: '100%', borderRadius: 10, alignItems: 'center', marginBottom: 8, borderWidth: 1, borderColor: '#e8dfd4' },
  closeButtonText: { color: '#7a5a3a', fontSize: 13, fontWeight: '600' },
  finishButton: { backgroundColor: '#3d2c1e', paddingVertical: 13, width: '100%', borderRadius: 10, alignItems: 'center' },
  finishButtonText: { color: '#faf8f4', fontSize: 14, fontWeight: '700' },

  // ── 재고 상품 리스트 스타일 ──
  productItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e8dfd4',
  },
  productIcon: { fontSize: 28, marginRight: 14 },
  productInfo: { flex: 1 },
  productName: { fontSize: 15, fontWeight: '700', color: '#3d2c1e', marginBottom: 4 },
  productPrice: { fontSize: 13, color: '#9e8c7a' },
  stockBadge: { backgroundColor: '#f5ede0', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  stockText: { fontSize: 12, fontWeight: '700', color: '#c47d4a' },
});